### ISSUE TITLE
No non-static method with name='setTagForChildProtection' 

### ISSUE THREAD

**Issue by m0skit0** [m0skit0/hms-sdk-unity#46]
```
2020-06-16 12:23:27.530 21836-21858/? E/Unity: AndroidJavaException: java.lang.NoSuchMethodError: no non-static method with name='setTagForChildProtection' signature='(I)Ljava/lang/Object;' in class Ljava.lang.Object;
    java.lang.NoSuchMethodError: no non-static method with name='setTagForChildProtection' signature='(I)Ljava/lang/Object;' in class Ljava.lang.Object;
        at com.unity3d.player.ReflectionHelper.getMethodID(Unknown Source:111)
        at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
        at com.unity3d.player.UnityPlayer.c(Unknown Source:0)
        at com.unity3d.player.UnityPlayer$e$2.queueIdle(Unknown Source:72)
        at android.os.MessageQueue.next(MessageQueue.java:479)
        at android.os.Looper.loop(Looper.java:144)
        at com.unity3d.player.UnityPlayer$e.run(Unknown Source:32)
      at UnityEngine._AndroidJNIHelper.GetMethodID (System.IntPtr jclass, System.String methodName, System.String signature, System.Boolean isStatic) [0x00041] in <dab6e33f2fe1419ba37fe57a1fcdecab>:0 
      at UnityEngine.AndroidJNIHelper.GetMethodID (System.IntPtr javaClass, System.String me
```

**Comment by m0skit0** [comment]
Fixed in commit 6e7cfa62a05130445c508fbbb3cb47c0ea7fbb47
